[server]
runOnSave = true

[client]
showErrorDetails = true
toolbarMode = "viewer"

[runner]
fastReruns = true

[theme]
primaryColor = "#f97316"
backgroundColor = "#fffbf5"
secondaryBackgroundColor = "#fff7ed"
textColor = "#1c1917"
font = "sans serif"
